I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 309, in script
    if seconddayfail + firstdayfail == 2:
  File "game/script.rpy", line 309, in <module>
    if seconddayfail + firstdayfail == 2:
NameError: name 'seconddayfail' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 309, in script
    if seconddayfail + firstdayfail == 2:
  File "/home/kotdath/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "/home/kotdath/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/kotdath/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 309, in <module>
    if seconddayfail + firstdayfail == 2:
NameError: name 'seconddayfail' is not defined

Linux-6.11.0-21-generic-x86_64-with-glibc2.39 x86_64
Ren'Py 8.3.7.25031702
lategame 1.0
Thu Apr  3 19:03:21 2025
